
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = "https://pilrzsqdqkxymjpnhklq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpbHJ6c3FkcWt4eW1qcG5oa2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjE2MjUsImV4cCI6MjA2NjU5NzYyNX0.P_6gIxOAdwyQfrei_dGZif6INlpe2PdPI_O0n_L_AQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
